"""change

Revision ID: 7636989ac8d0
Revises: a6a866865ea0
Create Date: 2021-11-12 15:05:16.816608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7636989ac8d0'
down_revision = 'a6a866865ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'comics_appeared_in',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'comics_appeared_in',
               existing_type=sa.String(length=200),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
