"""empty message

Revision ID: a6a866865ea0
Revises: b4f3a782e52b
Create Date: 2021-11-12 13:18:34.124864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6a866865ea0'
down_revision = 'b4f3a782e52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('comics_appeared_in', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('charCreation_date', sa.DateTime(), nullable=False),
    sa.Column('super_power', sa.String(length=100), nullable=True),
    sa.Column('team_affiliation', sa.String(length=100), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('comics_appeared_in', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('charCreation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('super_power', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('team_affiliation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], name='drone_user_token_fkey'),
    sa.PrimaryKeyConstraint('id', name='drone_pkey')
    )
    op.drop_table('character')
    # ### end Alembic commands ###
